---
- name: Build FindIt
  hosts: all

  roles:
    - { role: chruby, become: true, tags: ['chruby'] }
    - { role: apache, become: true , tags: ['apache']}
    - { role: passenger, tags: ['passenger'] }
    - { role: deploy-keys, tags: ['deploy-keys'], deploy_keys: "{{ findit_deploy_keys }}"}
    - { role: findit, tags: ['findit'] }
    - { role: shib, tags: ['shib'] }
    - { role: logrotate, tags: ['logrotate'] }
