---
- name: Build FindIt
  hosts: findit

  roles:
    - { role: chruby, become: true }
    - { role: apache, become: true }
    - { role: passenger, tags: ['passenger'] }
    - { role: deploy-keys, tags: ['deploy-keys']}
    - { role: findit, tags: ['findit'] }
    - { role: shib, tags: ['shib'] }
