---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/ansible-role-apache
  name: apache

- src: https://github.com/dheles/ansible-role-passenger
  name: passenger

- src: https://github.com/dheles/ansible-chruby.git
  name: chruby

- src: https://github.com/jhu-sheridan-libraries/findit-ansible-role
  name: findit

- src: https://github.com/dheles/deploy-keys-ansible-role
  name: deploy-keys
