---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/jhu-sheridan-libraries/ansible-role-login-user
  name: login-user

- src: https://github.com/jhu-sheridan-libraries/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/jhu-sheridan-libraries/ansible-role-apache
  name: apache

- src: https://github.com/jhu-sheridan-libraries/ansible-role-passenger
  name: passenger

- src: https://github.com/jhu-sheridan-libraries/ansible-chruby
  name: chruby

- src: https://github.com/jhu-sheridan-libraries/findit-ansible-role
  name: findit

- src: https://github.com/jhu-sheridan-libraries/deploy-keys-ansible-role
  version: v1.0.0
  name: deploy-keys

- src: https://github.com/jhu-sheridan-libraries/shibboleth-sp-ansible-role
  name: shib

- src: https://github.com/jhu-sheridan-libraries/logrotate-ansible-role
  name: logrotate
