---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: git@github.com:jhu-sheridan-libraries/ansible-role-login-user.git
  scm: git
  name: login-user

- src: git@github.com:jhu-sheridan-libraries/ansible-role-secure-ssh.git
  scm: git
  name: secure-ssh

- src: git@github.com:jhu-sheridan-libraries/ansible-role-apache.git
  scm: git
  name: apache

- src: git@github.com:jhu-sheridan-libraries/ansible-role-passenger.git
  scm: git
  name: passenger

- src: git@github.com:jhu-sheridan-libraries/ansible-chruby.git
  scm: git
  name: chruby

- src: git@github.com:jhu-library-devops/findit-ansible-role.git
  scm: git
  name: findit

- src: git@github.com:jhu-sheridan-libraries/deploy-keys-ansible-role.git
  name: deploy-keys
  scm: git

- src: git@github.com:jhu-sheridan-libraries/shibboleth-sp-ansible-role.git
  scm: git
  name: shib

- src: git@github.com:jhu-sheridan-libraries/logrotate-ansible-role.git
  scm: git
  name: logrotate
